language: go

go:
 - 1.13

env:
 global:
  - GO111MODULE=auto

before_install:
 - sudo apt-get install -y libvulkan-dev
 - git clone --depth=1 https://github.com/KhronosGroup/Vulkan-Headers.git ~/Vulkan-Headers
 - sudo rm -rf /usr/include/vulkan
 - sudo cp -r ~/Vulkan-Headers/include/vulkan /usr/include/

script:
 - go install  ./...
 - go test  ./...
